# No elimina tablas. 'update' actualiza la estructura de las tablas si agregas campos en la Entidad.
quarkus.hibernate-orm.database.generation=update

# Evita que import.sql se ejecute cada vez que arranca la aplicación si las tablas ya existen.
# 'never' es el valor recomendado cuando ya no quieres reinicializar datos.
quarkus.hibernate-orm.sql-load-script=no-file

# Opcional: Define explícitamente el manejo de esquema
quarkus.hibernate-orm.schema-management.strategy=update

# Motor de Base de Datos
quarkus.datasource.db-kind=postgresql

# Credenciales y Cadena de Conexión
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/customer_db

# Parámetros del Pool de Conexiones (Agroal)
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20